name: Manual workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  crypt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install staticrypt
      run: sudo npm install -g staticrypt
    - name: Encrypt index
      run: staticrypt main.html -p 1234567 --short -f password_template/template.html -o index.html
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: 'dragoncqh'
          destination-repository-name: 'StrivingWiki'
          user-email: dragoncqh@gmail.com
          target-branch: gh-pages
        
